runtime: go
api_version: go1

env: flex

handlers:
- url: /tour
  static_dir: 'kolmojs/build'
 
- url: /.*
  script: _go_app



# Update with Redis instance details
env_variables:
  REDISHOST: '10.0.0.3'
  REDISPORT: '6379'

  # Update with Redis instance network name
network:
  name: kolmold-vpc