#specify the runtime e.g. go,node,java,.NET etc
runtime: go
api_version: go1

env: flex

handlers:

- url: /
  static_files: public/index.html
  upload: public/index.html
 
- url: /.*
  script: _go_app

  


# Update with Redis instance details
env_variables:
  REDISHOST: '10.0.0.3'
  REDISPORT: '6379'

  # Update with Redis instance network name
network:
  name: default